### ISSUE TITLE
How does it works?

### ISSUE THREAD

**Issue by majsterkovic** [SimoDax/MSI-mystic-light-tool#11]
Hi!
I must download it and compile myself? How does it works? MSI Mystic Light is a service that works in background, and how about this program?
I've got MSI Mortat TITANUM with LEDs.

**Comment by SimoDax** [comment]
I stopped developing this project since https://github.com/ixjf/MSIRGB is now available, check it out. It doesn't need mystic light, so you can set any color or effect you want, no limitations
